---
- name: Primary Server Install
  hosts: localhost
  become: yes
  gather_facts: true

  tasks:
  - name: Standard Tasks
    include_role:
      name: basic_install

  - name: Install Containerization
    include_role:
      name: virtualization

  - name: Install Ansible
    include_role:
      name: automation

  - name: Install Containers
    include_role:
      name: primary_server
